// Copies contract ABIs from the Foundry build (../out) into src/lib/abis.ts.
// Run `forge build` in the repo root first, then `npm run sync-abis`.
import { readFileSync, writeFileSync } from "node:fs";

const contracts = ["CurtainEvent", "CurtainFactory"];
let out = "// Generated by scripts/sync-abis.mjs from the Foundry build. Do not edit.\n";
for (const name of contracts) {
  const { abi } = JSON.parse(readFileSync(new URL(`../../out/${name}.sol/${name}.json`, import.meta.url), "utf8"));
  out += `\nexport const ${name[0].toLowerCase()}${name.slice(1)}Abi = ${JSON.stringify(abi, null, 2)} as const;\n`;
}
writeFileSync(new URL("../src/lib/abis.ts", import.meta.url), out);
console.log(`wrote src/lib/abis.ts (${contracts.join(", ")})`);
